export const filtersInitialState = {
  price: 0,
  Background: [
    { title: "All", selected: true, id: 0 },
    { title: "Desert", selected: false, id: 1 },
    { title: "Purple", selected: false, id: 2 },
    { title: "Yellow", selected: false, id: 3 },
    { title: "Green", selected: false, id: 4 },
    { title: "Red", selected: false, id: 5 },
    { title: "Cyan", selected: false, id: 6 },
    { title: "Blue", selected: false, id: 7 },
    { title: "City", selected: false, id: 8 },
    { title: "Dark Green", selected: false, id: 9 },
    { title: "Pinkk", selected: false, id: 10 },
    { title: "Navy", selected: false, id: 11 },
    { title: "Orange", selected: false, id: 12 },
    { title: "Clouds", selected: false, id: 13 },
    { title: "Dawn", selected: false, id: 14 },
    { title: "Space", selected: false, id: 15 },
  ],
  Floki: [
    { title: "All", selected: true, id: 0 },
    { title: "Pink Blue", selected: false, id: 1 },
    { title: "Purple", selected: false, id: 2 },
    { title: "Brown Pink", selected: false, id: 3 },
    { title: "Yellow Green", selected: false, id: 4 },
    { title: "Blue White", selected: false, id: 5 },
    { title: "Brown Grey", selected: false, id: 6 },
    { title: "Grey Pink", selected: false, id: 7 },
    { title: "Rainbow", selected: false, id: 8 },
    { title: "Yellow Orange", selected: false, id: 9 },
    { title: "Green Purple", selected: false, id: 10 },
    { title: "Orange White", selected: false, id: 11 },
    { title: "Orange Green", selected: false, id: 12 },
    { title: "Green Yellow", selected: false, id: 13 },
    { title: "Black Brow", selected: false, id: 14 },
    { title: "Hot Pink Blue", selected: false, id: 15 },
    { title: "Blue Orange", selected: false, id: 16 },
    { title: "Violet Green", selected: false, id: 17 },
    { title: "Zombie", selected: false, id: 18 },
    { title: "Blue", selected: false, id: 19 },
    { title: "Grey White", selected: false, id: 20 },
    { title: "White Grey", selected: false, id: 21 },
    { title: "Red Orange", selected: false, id: 22 },
    { title: "Red White", selected: false, id: 23 },
  ],

  Head: [
    { title: "All", selected: true, id: 0 },
    { title: "Party Hat", selected: false, id: 1 },
    { title: "Bucket Hat", selected: false, id: 2 },
    { title: "Baseball Cap", selected: false, id: 3 },
    { title: "Top Hat", selected: false, id: 4 },
    { title: "Jester Hat", selected: false, id: 5 },
    { title: "Cowboy Hat", selected: false, id: 6 },
    { title: "Sombrero", selected: false, id: 7 },
    { title: "Crown", selected: false, id: 8 },
    { title: "Headband", selected: false, id: 9 },
    { title: "Headphones", selected: false, id: 10 },
    { title: "Brunette Lady", selected: false, id: 11 },
    { title: "Flower", selected: false, id: 12 },
    { title: "Mohawk", selected: false, id: 13 },
    { title: "Bird", selected: false, id: 14 },
    { title: "Blonde Lady", selected: false, id: 15 },
  ],
  Eyes: [
    { title: "All", selected: true, id: 0 },
    { title: "Nerd Glasses", selected: false, id: 1 },
    { title: "Sunglasses", selected: false, id: 2 },
    { title: "Ski Goggles", selected: false, id: 3 },
    { title: "Monocle", selected: false, id: 4 },
    { title: "Diving Goggles", selected: false, id: 5 },
    { title: "Eyepatch", selected: false, id: 6 },
    { title: "Blue Eye", selected: false, id: 7 },
    { title: "Cyclops Glasses", selected: false, id: 8 },
    { title: "Pilot Glasses", selected: false, id: 9 },
    { title: "Brown Eyes", selected: false, id: 10 },
    { title: "Green Eyes", selected: false, id: 11 },
  ],
  Wristband: [
    { title: "All", selected: true, id: 0 },
    { title: "Wristband", selected: false, id: 1 },
  ],
  Mouth: [
    { title: "All", selected: true, id: 0 },
    { title: "Pipe", selected: false, id: 1 },
    { title: "Cigarette", selected: false, id: 2 },
    { title: "Tongue Out", selected: false, id: 3 },
  ],
  Tattoo: [
    { title: "All", selected: true, id: 0 },
    { title: "Anchor Tattoo", selected: false, id: 1 },
    { title: "Heart Tattoo", selected: false, id: 2 },
  ],
};

export const filterKeys = {
  Background: [
    "No Background",
    "Desert",
    "Purple",
    "Yellow",
    "Green",
    "Red",
    "Cyan",
    "Blue",
    "City",
    "Dark Green",
    "Pinkk",
    "Navy",
    "Orange",
    "Clouds",
    "Dawn",
    "Space",
  ],
  Floki: [
    "No Floki",
    "Pink Blue",
    "Purple",
    "Brown Pink",
    "Yellow Green",
    "Blue White",
    "Brown Grey",
    "Grey Pink",
    "Rainbow",
    "Yellow Orange",
    "Green Purple",
    "Orange White",
    "Orange Green",
    "Green Yellow",
    "Black Brow",
    "Hot Pink Blue",
    "Blue Orange",
    "Violet Green",
    "Zombie",
    "Blue",
    "Grey White",
    "White Grey",
    "Red Orange",
    "Red White",
  ],
  Head: [
    "No Head ",
    "Party Hat",
    "Bucket Hat",
    "Baseball Cap",
    "Top Hat",
    "Jester Hat",
    "Cowboy Hat",
    "Sombrero",
    "Crown",
    "Headband",
    "Headphones",
    "Brunette Lady",
    "Flower",
    "Mohawk",
    "Bird",
    "Blonde Lady",
  ],
  Eyes: [
    "No Eyes",
    "Nerd Glasses",
    "Sunglasses",
    "Ski Goggles",
    "Monocle",
    "Diving Goggles",
    "Eyepatch",
    "Blue Eye",
    "Cyclops Glasses",
    "Pilot Glasses",
    "Brown Eyes",
    "Green Eyes",
  ],
  Wristband: ["No Wristband ", "Wristband"],
  Mouth: ["No Mouth ", "Pipe", "Cigarette", "Tongue Out"],
  Tattoo: ["No Tattoo ", "Anchor Tattoo", "Heart Tattoo"],
};
